### ISSUE TITLE
Tray breaks when barista sends it before placing cup down

### ISSUE THREAD

**Issue by outfrost** [outfrost/ld49#46] opened 2021-10-05 03:22 UTC
"Send it" command queues up on the tray before cup is placed down?

**Comment by 666Savior** [comment] 2021-10-11 05:31
Seems to be something with the is_handsEmpty() method on the player character. Tray checks for this to be empty before sending. 
It might not be properly updating while transitioning quickly from picking coffee to moving to the tray and clicking the tray before movement is complete?
There is a possibility that my changes to the tray empty check fixed this but not confirmed.

**Comment by L1Q** [comment] 2021-10-15 05:02
The entire queue system is broken like that. I'm thinking either check for conditions again when it's time to pop an item from the queue or drop the whole queue concept completely - it doesn't seem to fit the pacing anyway.

**Comment by 666Savior** [comment] 2021-10-30 18:33
Should be fixed with change to clicking customer to call for order

**Closed by 666Savior** 2021-10-30 18:33 UTC
Labels: bug
